### ISSUE TITLE
Handle similar names for favorite beers

### ISSUE THREAD

**Issue by overflorian** [OpenBeerMap/OpenBeerMap.github.io#48]
While looking for my favourite beer I found out that I have to make several filters only to display one kind of beer.

![screenshot_2015-06-16-18-10-00](https://cloud.githubusercontent.com/assets/11553211/8188086/e5be8fa0-1453-11e5-9654-fcf3ff729dbf.png)

It would be nice to optimise your query to handle MAJ and approximative spelling.
Thanks ;)

**Comment by nlehuby** [comment]
Hi Florian !

Thanks for your feedback.

This feature did exist in the past (see how we handled [Kronenbourg / Kronembourg](https://github.com/OpenBeerMap/OpenBeerMap.github.io/blob/06a55179a12359c4b9452bc6bf876205b58175d0/assets/js/BeerList.js#L70) for instance)

But the answer should be in the data rather than in the query (all these variantes should not exist in the database).

As OpenBeerMap does not know all the beers existing in the world, we must let the users enter any beer with any spelling in the database.
So ... we have to perform some moderation to uniformize the beers names.

This already has been [done in the past](https://www.openstreetmap.org/user/OpenBeerMapContributor/diary/22264) but this is an endless mission ... (BTW, I'm recruiting on this subject : any beer lover + OSM contributor can help !)
Feel free to take over this job for your favorite beers ;)

**Comment by overflorian** [comment]
I did my part: http://www.openstreetmap.org/changeset/32032236
Does it make me part of the OBM community ? ^^

**Comment by nlehuby** [comment]
The OBM community admission fee includes :
* moderating a few contributions
* demonstrating OBM on a friend phone/laptop
* and offering me a beer

oh and this is a monthly fee, of course ;)

Thanks for your contribution.

**Comment by overflorian** [comment]
I am afraid I only managed the second point. But I did it A LOT these days.
Will you be at tonight's meetup ? http://www.eventbrite.fr/e/billets-meetup-open-transport-5-capteurs-territoires-17200107986?aff=twt
If so I'll offer you a beer. I really want to be part of the community ^^

**Comment by nlehuby** [comment]
nope, but I'm sure we'll find many oportunities to see each other in the future months ;)

**Comment by overflorian** [comment]
We sure did.

**Comment by bmillemathias** [comment]
So, now you plan to create an app OpenSpritzMap considering sprtitz became a thing meanwhile. :)

**Comment by overflorian** [comment]
> So, now you plan to create an app OpenSpritzMap considering sprtitz became a thing meanwhile. :)

I think we'll stick with beer because "90% of the FLOSS issues are solvable in hop", dixit Tristan Nitot
